# Next steps

```{r, include = FALSE}
knitr::opts_chunk$set(fig.width=6, fig.height=3.5, fig.align="center")
```

## How to find help

* The best source for basics is the book [R for Data Science](https://r4ds.had.co.nz/)

* To see the documentation for a function, execute the function with a "?" in front of it like this: ?geom_boxplot

* When you don't know what command to use, or the documentation doesn't help, use Google. 

* In web searches, include the words "tidy" or "ggplot" in your search, like "ggplot boxplot". Unfortunately searching "R" isn't very specific.

* Results from stackoverflow.com are usually good discussions among users

* Web search results from tidyverse.org are good, but they're usually just the documentation

* If you find plotting results that don't use ggplot, I suggest ignoring them for now. It's hard to learn two different plotting methods. 

* Check out [RStudio's collection of cheat sheets](https://www.rstudio.com/resources/cheatsheets/) cover newer packages in R.


## General strategies

View a few rows of your data frequently.

Plot your data frequency. Plot it in different ways.

When you find something interesting, try to disprove what you've found. This will help strengthen your evidence and understanding of your result.



